
services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
      - redis
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      WP_TITLE: ${WP_TITLE}
      WP_URL: ${WP_URL}

  nginx:
    build: requirements/nginx
    container_name: nginx
    restart: unless-stopped
    env_file: .env
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
      - adminer
      - static-site

  # Bonus Services
  redis:
    build: requirements/bonus/redis
    container_name: redis
    restart: unless-stopped
    networks:
      - inception
    environment:
      REDIS_PASSWORD: redispassword123

  ftp:
    build: requirements/bonus/ftp
    container_name: ftp
    restart: unless-stopped
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    environment:
      FTP_USER: ftpuser
      FTP_PASSWORD: ftppassword123

  adminer:
    build: requirements/bonus/adminer
    container_name: adminer
    restart: unless-stopped
    networks:
      - inception
    depends_on:
      - mariadb

  static-site:
    build: requirements/bonus/static-site
    container_name: static-site
    restart: unless-stopped
    networks:
      - inception

  portainer:
    build: requirements/bonus/portainer
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9443:9000"   # external:internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - inception
    environment:
      PORTAINER_PASSWORD: ${PORTAINER_PASSWORD}

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MYSQL_DATA_PATH}
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WP_DATA_PATH}
  portainer_data:   # <-- no driver_opts here, Docker will handle it

networks:
  inception:
    driver: bridge